name: Repository Dispatch
on:
  repository_dispatch:
    types: [ dispatch ]
jobs:
  fetcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Install the latest version of rye
        id: setup-rye
        uses: eifinger/setup-rye@v3
        with:
          enable-cache: true
      - name: Sync rye
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: rye sync
      - run: .venv/bin/python src/main.py
