name: Repository Dispatch
on:
  repository_dispatch:
    types: [ dispatch ]
jobs:
  fetcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Install the latest version of rye
        id: setup-rye
        uses: eifinger/setup-rye@v3
        with:
          enable-cache: true
      - name: Sync rye
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: rye sync
      - run: .venv/bin/python src/main.py
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
          MANADA_PWD: ${{ secrets.MANADA_PWD }}
          MANADA_URL: ${{ secrets.MANADA_URL }}
          MANADA_USER: ${{ secrets.MANADA_USER }}
          NOTICE_URL: ${{ secrets.NOTICE_URL }}

